# Generated by Django 5.1.3 on 2025-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
